#! /bin/bash

date
date1=$(date +"%s")

echo Calculating black hole shadow

rm bh_shadow_run
cp bh_shadow bh_shadow_run

#./bh_shadow_run
./bh_shadow_run +RTS -N4 #-s

date
echo Finished
date2=$(date +"%s")
diff=$(($date2-$date1))
echo "$(($diff / 60)) minutes and $(($diff % 60)) seconds."
